name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install linter
        run: sudo npm install htmlhint -g

      - name: Lint webpage
        run: htmlhint www/index.html
